# gitpod.io/#github.com/CaravanaCloud/red-pod
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Welcome
    init: |
      mkdir -p "$HOME/.kube"
      ln -sf "$GITPOD_REPO_ROOT/auth/kubeconfig" "$HOME/.kube/config"
      echo "Init okd-pod at $(date)"
    command: echo "Hello red-pod :)"

ports:
  - port: 8080
    onOpen: ignore
    visibility: public


vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode

