rm -f *.tfvars.json
rm -f terraform.*
rm -f .openmshift_install_state.json
rm -f .openshift_create-cluster.log
rm -f .openshift_install.log
rm -rf tls
rm -f metadata.json
rm -f payload.json
rm -f log-bundle*.tar.gz
rm -rf k7r-poc/.*.json
rm -rf .*.csv
rm -rf .*.yaml
rm -rf data/*
rm -rf .cco-out
rm -rf .cco-requests
