apiVersion: v1
baseDomain: $BASE_DOMAIN
credentialsMode: Manual

metadata:
  name: $CLUSTER_NAME

platform:
  aws:
    region: $AWS_REGION

publish: External
pullSecret: '$PULL_SECRET'
sshKey: |
  $SSH_KEY
